import type { NextPage } from "next";
import Head from "next/head";
import { BaseLayout } from "../components/BaseLayout";
import { Skills } from "../components/Skills";
import { AboutMe } from "../components/AboutMe";

const Home: NextPage = () => {
  return (
    <BaseLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AboutMe />
      <h1>Technologies I know</h1>
      <Skills />
      <h1>Education</h1>
      <h1>Contact</h1>
    </BaseLayout>
  );
};

export default Home;
